CREATE SEQUENCE seq_oficina_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_empleado_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_departamento_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_contrato_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_nomina_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_vacaciones_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_tecnologia_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_formacion_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_evaluacion_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_cliente_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_proyecto_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_material_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


CREATE OR REPLACE TRIGGER trg_oficina_id
BEFORE INSERT ON Oficina
FOR EACH ROW
BEGIN
    SELECT 'OFI-' || LPAD(seq_oficina_id.NEXTVAL, 5, '0') INTO :NEW.ID_oficina FROM dual;
END;
/

CREATE OR REPLACE TRIGGER trg_info_empleado_personal_id
BEFORE INSERT ON Info_Empleado_Personal
FOR EACH ROW
BEGIN
    SELECT 'EMP-' || LPAD(seq_empleado_id.NEXTVAL, 5, '0') INTO :NEW.ID_empleado FROM dual;
END;
/

CREATE OR REPLACE TRIGGER trg_departamento_id
BEFORE INSERT ON Departamento
FOR EACH ROW
BEGIN
    SELECT 'DEP-' || LPAD(seq_departamento_id.NEXTVAL, 5, '0') INTO :NEW.ID_departamento FROM dual;
END;
/

CREATE OR REPLACE TRIGGER trg_contrato_id
BEFORE INSERT ON Contrato
FOR EACH ROW
BEGIN
    SELECT 'CON-' || LPAD(seq_contrato_id.NEXTVAL, 5, '0') INTO :NEW.ID_contrato FROM dual;
END;
/

CREATE OR REPLACE TRIGGER trg_nomina_id
BEFORE INSERT ON Nomina
FOR EACH ROW
BEGIN
    SELECT 'NOM-' || LPAD(seq_nomina_id.NEXTVAL, 5, '0') INTO :NEW.ID_nomina FROM dual;
END;
/

CREATE OR REPLACE TRIGGER trg_vacaciones_id
BEFORE INSERT ON Vacaciones
FOR EACH ROW
BEGIN
    SELECT 'VAC-' || LPAD(seq_vacaciones_id.NEXTVAL, 5, '0') INTO :NEW.ID_vacaciones FROM dual;
END;
/

CREATE OR REPLACE TRIGGER trg_tecnologia_id
BEFORE INSERT ON Tecnologia
FOR EACH ROW
BEGIN
    SELECT 'TEC-' || LPAD(seq_tecnologia_id.NEXTVAL, 5, '0') INTO :NEW.ID_tecnologia FROM dual;
END;
/

CREATE OR REPLACE TRIGGER trg_formacion_id
BEFORE INSERT ON Formacion
FOR EACH ROW
BEGIN
    SELECT 'FOR-' || LPAD(seq_formacion_id.NEXTVAL, 5, '0') INTO :NEW.ID_Formacion FROM dual;
END;
/

CREATE OR REPLACE TRIGGER trg_evaluacion_id
BEFORE INSERT ON Evaluacion
FOR EACH ROW
BEGIN
    SELECT 'EVA-' || LPAD(seq_evaluacion_id.NEXTVAL, 5, '0') INTO :NEW.ID_evaluacion FROM dual;
END;
/

CREATE OR REPLACE TRIGGER trg_cliente_id
BEFORE INSERT ON Cliente
FOR EACH ROW
BEGIN
    SELECT 'CLI-' || LPAD(seq_cliente_id.NEXTVAL, 5, '0') INTO :NEW.ID_cliente FROM dual;
END;
/

CREATE OR REPLACE TRIGGER trg_proyecto_id
BEFORE INSERT ON Proyecto
FOR EACH ROW
BEGIN
    SELECT 'PRO-' || LPAD(seq_proyecto_id.NEXTVAL, 5, '0') INTO :NEW.ID_proyecto FROM dual;
END;
/

CREATE OR REPLACE TRIGGER trg_material_id
BEFORE INSERT ON Material
FOR EACH ROW
BEGIN
    SELECT 'MAT-' || LPAD(seq_material_id.NEXTVAL, 5, '0') INTO :NEW.ID_material FROM dual;
END;
/

